### ISSUE TITLE
Broken: Install_fixpack (action does not have the right set of arguments or there is a code bug!)

### ISSUE THREAD

**Issue by CoolZeroNL** [IBM-Security/ibmsecurity#197]
The module install_fixpack is Failing, when i not enforcing the role (force=false). But when i'm enforcing the role (force=true), then the role will apply and install the fixpack with no errors.

What arguments is missing in the role `install_fixpack` or is it a bug?

**Error msg:**
```
Action does not have the right set of arguments or there is a code bug! Options: isamAppliance=isam_server, force=False, file="/tmp/9070_IF1.fixpack"
```
**Yml using:**
https://gist.github.com/CoolZeroNL/80f9576e1c07a9faf6ab813a888bef91

**logging: force = false**
https://gist.github.com/CoolZeroNL/493a56e71a9b2ced20cff32abdeaea72

**logging: force = true**
https://gist.github.com/CoolZeroNL/81336a55c81b0f65fc3324b293c9d42d

**Comment by sygilber** [comment]
Hello CoolZeroLN

I'm using on a regular basis the role 'install_fixpack' without any issue, and also lately with 907_IF1 and other interim fixes.

By analysing your shared stack trace, we can see that when **force = false**, we are not by-passing the _check() method invocation (whereas we do when **force = true**). The role of the check() method is just to determine if the fixpack you are trying to apply is already uploaded on the Appliance and if so, if it is installed so that it could skip the step for idempotency. For doing so, it needs to compute the actual fixpack name on the Appliance and the one of your fixpack file .
So, the crash in your case happen while python code is trying to figure out the "official* fixpack name by either inspecting the actual content of the file, and if failing, it will assume the fixpack basename of file name as the *official* fixpack name. If we dig further in your stack trace, the crash occurs inside the utility ibmsecurity.utilities.tools.strings() which attempt at opening the fix pack file in read and binary mode, then uses “if c in string.printable”. The fixpack file contains a file name fixpack.info which looks like this:
FIXPACK_ID="9070_IF1"
FIXPACK_NAME="9070_IF1"
FIXPACK_DESCRIPTION="This fixpack provides security updates to 9070 version appliance. It also contains a few APAR fixes."
FIXPACK_FIRMWARE_VERSION="9.0.7.0"
IGNORE_MISSING_FILES=1

Now I am kind of in the dark as to what could be happening here and therefore maybe we need a bit more context. 

a)	What is the python version you are using ?

We have opportunity to add robustness to the code (such as catching i/o errors during execution of ibmsecurity.utilities.tools.strings() and fall back to use the fixpack file name) but before, we need to better understand what external factor (?) is driving the code to behave this way. 9070_IF1 fixpack file is 200+ MB in size so many things can occur that make things go bad (no enough memory, disk, etc.).
Ps: I don’t think you are missing any additional argument.

Thanks

**Comment by CoolZeroNL** [comment]
Check, thanks for the explaining of the force function.

I'm using:
- ansible-playbook 2.9.1
- python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]

Disk space and memory is more then enough that wont be the problem.

I figger it out, the code that is been used for the strings is python 2.x i'm using 3.x.

In the function there is now code for python 2.x this wont work for python 3.x: 
```
with open(filename, "rb") as f:           # Python 2.x
```

code line that will work with pyhton 3
```
with open(filename, errors="ignore") as f:  # Python 3.x
```

**Comment by sygilber** [comment]
So to wrap things up, we have 2 issues:

a) with open(...)

There are multiple spots where we are doing "with open(...) the Python v2.7 way:

> ./appliance/isdsappliance.py:                with open(filename, 'wb') as f:
> ./appliance/isamappliance.py:                with open(filename, 'wb') as f:
> ./appliance/isamappliance.py:                        with open(filename, 'wb') as f:
> ./isam/aac/access_control/policies.py:    with open(policy_file, 'r') as myfile:
> ./isam/aac/authentication/policies.py:    with open(policy_file, 'r') as myfile:
> ./isam/aac/mapping_rules.py:            with open(upload_filename, 'r') as contentFile:
> ./isam/aac/mapping_rules.py:            with open(filename, 'r') as infile:
> ./isam/aac/policy_information_points/javascript.py:            with open(filepath, 'r') as infile:
> ./isam/aac/access_policy.py:            with open(file, 'r') as contentFile:
> ./isam/aac/access_policy.py:            with open(file, 'r') as infile:
> ./isam/base/license.py:    with open(license, 'rt') as f:
> ./isam/fed/federations.py:    with open(filename, 'r') as infile:
> ./isam/web/authorization_server/configuration/trace.py:            with open(filepath, 'r') as infile:
> ./isam/web/runtime/trace.py:            with open(filepath, 'r') as infile:
> ./utilities/tools.py:    with open(original_file, 'r') as f:
> ./utilities/tools.py:    with open(new_file, 'r') as f:
> ./utilities/tools.py:    with open(filename, "rb") as f:

I need to research a bit more on this to find out the best way to resolve this, in a compatible manner. I a kind of discouraged that such basic utility in Python could not be ported in a compatible way in 3.8. This link suggests it may still be supported. Is it really ?  https://docs.python.org/3/tutorial/inputoutput.html


b) strings

=> Need to find a replacement and/or compatible way of using "strings". @ram-ibm, is finding the official FP name by inspecting the inner files of the fixpack file truely crucial ? Do we want to preserve this logic at all cost, or could we not simply not rely on the fix pack file name ? 

I am not setup for Python 3.8 testing to conduct code/fixes for 3.8.

**Comment by CoolZeroNL** [comment]
Could be that this issue is only to binary files?. I have no issues for example with the license.py.

I found that the module `codecs`.open is supported for python 2 and python 3

```
import codecs
codecs.open(filename, 'rb', errors = 'ignore')
```

I'v tested this with python 2.7 & python 3.6 and gives me no errors.
```
def strings(filename, min=4):
    """
    Emulate UNIX "strings" command on a file
    """
    with codecs.open(filename, 'rb', errors = 'ignore') as f:
        result = ""
        for c in f.read():
            if c in string.printable:
                result += c
                continue
            if len(result) >= min:
                yield result
            result = ""
        if len(result) >= min:  # catch result at EOF
            yield result
```

**Comment by CoolZeroNL** [comment]
so i have been testing. 

I setup a new clean environment (centos 7 + pyenv) so i can test it with multiple version of Python.

```
ansible-playbook 2.9.2
ansible python module location = /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/ansible
executable location = /root/.pyenv/versions/3.6.8/bin/ansible-playbook
python version = 3.6.8 (default, Dec  6 2019, 05:41:00) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
[urllib3.connectionpool] [_make_request():428] https://demo.isam.com:443 "POST /fixpacks HTTP/1.1" 200 0

```
ansible-playbook 2.9.2
   ansible python module location = /root/.pyenv/versions/3.8.0/lib/python3.8/site-packages/ansible
  executable location = /root/.pyenv/versions/3.8.0/bin/ansible-playbook
  python version = 3.8.0 (default, Dec  6 2019, 02:59:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
[urllib3.connectionpool] [_make_request():428] https://demo.isam.com:443 "POST /fixpacks HTTP/1.1" 200 0

```
ansible-playbook 2.9.2
  ansible python module location = /root/.pyenv/versions/2.7.17/lib/python2.7/site-packages/ansible
  executable location = /root/.pyenv/versions/2.7.17/bin/ansible-playbook
  python version = 2.7.17 (default, Dec  6 2019, 02:54:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```
I get here a little difference STDOUT back, but no error. And if i look in ISAM the fixpack is installed.

so, dont know why the install_fixpack failes on my ubuntu system.

**Comment by ram-ibm** [comment]
The python2 to 3 conversion process missed file open(). So a analysis of the entire package is being performed to see where else we see the issue faced with fixpack installs.

The fixpack installs itself uses "strings" ability to look for FIXPACK_NAME inside the file or default to filename as the worst case. This was done since some fixpacks had a different name after install versus the physical fixpack file name as provided from IBM Support.

**Comment by sygilber** [comment]
Hi - I was sick not being able to run our own playbooks under Python 3.6 so I built myself my little sandbox (CentOS 8 in a local VM with pyenv installed to be able to switch easily between Python versions). Now I am focusing my attention on Python V3.6.8.

Already did lots of cleanup on our end, and I should say that our playbooks with no file i/o run properly, while some with file i/o work and some not. So I am trying to figure out what is proper pattern in Python v3.6 for "with open()"  ?

I believe we should resolve this first, then the _strings_ utility.

**Comment by djorgen-ibm** [comment]
The updates associated with open() for Python 3 compatibility were merged.
